import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LoadingBar } from "@/components/common/LoadingBar";
import { ThemeProvider } from "next-themes";
import { SmoothScroll } from "@/components/common/SmoothScroll";
import { GoogleTagManager } from "@next/third-parties/google";
import { Breadcrumbs } from "@/components/common/BreadCrumbs";
import { fetchStrapi } from "@/lib/strapi";
import { StrapiResponse, ServiceHub } from "@/types";
import { NavbarClient } from "@/components/NavbarClient";
import { Footer } from "@/components/common/Footer";

const GTM = process.env.NEXT_PUBLIC_GTM || "GTM-TJF7Q4JF";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const navData: StrapiResponse<ServiceHub> = await fetchStrapi("service-hubs", {
  populate: ["service_pages"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <GoogleTagManager gtmId={GTM} />
      <body className="min-h-full flex flex-col">
        <LoadingBar />
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <SmoothScroll>
            <NavbarClient navItems={navData.data} />
            <Breadcrumbs />
            <main className="flex-1">{children}</main>
            <Footer navItems={navData.data} />
          </SmoothScroll>
        </ThemeProvider>
        <div id="portal-root"></div>
      </body>
    </html>
  );
}
